### ISSUE TITLE
dump original firmware

### ISSUE THREAD

**Issue by nicolasroche898** [Andrik45719/MJSXJ03HL#2]
Is it possible to dump original firmware without modifying bootloader?

so if I do this:
* delete the file demo_hlc7_boot.bin, 
* keep only the file boot.scr

will it work?

I want to backup the orignal firmware without modifying anything, so i can verify it first.

**Comment by Andrik45719** [comment]
Unfortunately no, stock u-boot not call boot.scr script.
You can build your own kernel image with boot loader backup functionality and load it at booting.
Stock u-boot loads file factory_t31_ZMC6tiIDQN from mmc and execute it.
factory_t31_ZMC6tiIDQN is u-boot linux kernel image.
I am uploaded stock u-boot for research (xiaomi_mjsxj03hl_t31zl_uboot.bin).

**Comment by nicolasroche898** [comment]
I've successfully installed firmware on fresh camera, thanks to your detailed instructions.

**Comment by Andrik45719** [comment]
> Is it possible to dump original firmware without modifying bootloader?
> 
> so if I do this:
> 
> * delete the file demo_hlc7_boot.bin,
> * keep only the file boot.scr
> 
> will it work?
> 
> I want to backup the orignal firmware without modifying anything, so i can verify it first.

Hi, flashing method is updated, original bootloader not modified in the stock fw dump
